### ISSUE TITLE
endpoints

### ISSUE THREAD

**Issue by Kadantte** [gokoro/Ohys-Server#1]
Hi I just want to try this API locally anyway I get the [`parser`](https://github.com/gokoro/Ohys-Parse) to be running after that I started the [`server`](https://github.com/gokoro/Ohys-Server) but it looks like the server doesn't return anything it might be during to routes doesn't been configured or something As you see in this picture [001](https://candyseul.is-inside.me/mgrHr603.png) Also [`schedule`](https://github.com/gokoro/Ohys-Schedule) is running on my local but it looks like as I said it doesn't get any data from the server! [002](https://candyseul.is-inside.me/UOpQPH0e.png) here I included some pictures!

**Comment by gokoro** [comment]
**TD;DR Run the following commands on your console!**
```
git checkout release/rest
yarn
```

The actual problem is due to that I updated this API. I've made GraphQL API endpoint of Ohys-Server and pushed it into `master` branch. I intended to make the frontend client suited for this, But It wasn't an easy work. That's because this server isn't working for the client of current version.

I have fixed this problem and created branch `release/rest` to use the previous api with REST. All you need to do is checkout into that branch and reinstall the dependencies, and it will work well!

Anyway, Thank you for your interest on this project! 😄

**Comment by Kadantte** [comment]
Thank you very much for your answer and for your new branch that fixes this problem, Well I was looking for a way to keep me updated about Ohys releases and I came across your code :3 I have a local server that keeps this running for my local network anyway I have on it some other stuff like LANraragi xD and more useful tools! Again thank u so much for making this lovely tool :3
